/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mptnhektozvjowoydjha"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wdG5oZWt0b3p2am93b3lkamhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUzMDI1NjUsImV4cCI6MjA4MDg3ODU2NX0.3x9Z3IAJL88-Jk7bwaBfbr4ZD-UlQ3g1USf2h8BQ_DA"